f=open("one.txt","r")
data=f.read()
print("file content: ",data)
f.close()
#readline
f=open("two.txt","r")
line1=f.readline()
line2=f.readline()
line3=f.readline()
print("line 1:",line1)
print("line 2:",line2)
print("line 3:",line3)
f.close()
#readlines
f=open("one.txt","r")
lines=f.readlines()
print("list of lines:",lines)
print("number of lines:",len(lines))
f.close()
#write
f=open("one.txt","w")
f.write("hello students.\n")
f.write("welcome to python programming.\n")
f.write("learning is fun!.\n")
f.close()
#copy
src=open("one.txt","r")
data=src.read()
src.close()
dst=open("bit.txt","w")
dst.write(data)
dst.close()
print("file copied succesfully..") 
#merge
with open("one.txt","r") as f1,open("two.txt","r") as f2,open("create.txt","w") as f3:
    f3.write(f1.read())
    f3.write("\n")
    f3.write(f2.read())
 print("files merged successfully...")